remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme


title: è¾°å·³å®¶ CODR
description: Mirco software service studio based in Kaohsiung, TaiwanğŸ§‹
footer: åˆä½œè«‹æ´½ hi [at] codr.tw
tax_info: çµ±ä¸€ç·¨è™Ÿ 00111446
